# Generated by Django 2.1.2 on 2018-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('destination1', models.CharField(max_length=40)),
                ('destination2', models.CharField(max_length=40)),
                ('destination3', models.CharField(max_length=40)),
                ('destination4', models.CharField(max_length=40)),
                ('destination5', models.CharField(max_length=40)),
                ('destination6', models.CharField(max_length=40)),
                ('destination7', models.CharField(max_length=40)),
                ('destination8', models.CharField(max_length=40)),
                ('destination9', models.CharField(max_length=40)),
                ('destination10', models.CharField(max_length=40)),
                ('no_of_destinations', models.IntegerField()),
                ('weight1', models.IntegerField()),
                ('weight2', models.IntegerField()),
                ('weight3', models.IntegerField()),
                ('weight4', models.IntegerField()),
                ('weight5', models.IntegerField()),
                ('weight6', models.IntegerField()),
                ('weight7', models.IntegerField()),
                ('weight8', models.IntegerField()),
                ('weight9', models.IntegerField()),
                ('weight10', models.IntegerField()),
                ('capacityOfTruck', models.IntegerField()),
            ],
        ),
    ]
